/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ortiz Morales
 */
public class Applet extends java.applet.Applet {

    /**
     * Initializes the applet Applet
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTn1 = new javax.swing.JTextField();
        JTn2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTn3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTn4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JB1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        JTn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(JTn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 200, -1));

        JTn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(JTn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 200, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese DPI");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        JTn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(JTn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Edad");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        JTn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(JTn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese Direccion de Domicilio");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        JB1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        JB1.setText("Ingresar Datos");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 204));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        String nombre, direccion;
        int dpi, edad;
        nombre = JTn1.getText();
        dpi = Integer.parseInt(JTn2.getText());
        dpi = Integer.parseInt(JTn2.getText());
        direccion = JTn4.getText();
    }//GEN-LAST:event_JB1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JTextField JTn1;
    private javax.swing.JTextField JTn2;
    private javax.swing.JTextField JTn3;
    private javax.swing.JTextField JTn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
